### ISSUE TITLE
mainwindow 설정에 대해서.

### ISSUE THREAD

**Issue by kokosoko59** [babmukgohazo/pmind#6]
저번 회의에서, editscreen을 mainwindow로 하고싶다고 얘기를 했었는데 이게 서로 제대로 전달된것이 맞는지 확인좀 할게요. 잘못 이해하고 있는게 있다면 지적 바랍니다. @JinSungkwang @jisoooo 

프로그램 동작
1. 프로그램 동작 중에는 항상 메뉴바, 스테이터스바를 가지고 있는 edit 화면이 뜨도록 한다.
2. 프로그램 실행 시 메뉴선택 위젯이 나온다. (지금 지수가 만든 filemanage.ui와 같은 것. 이때도 edit화면은 메뉴선택 화면 아래에 떠 있는 상태.)

프로그램 구현 및 문제사항
1. 정훈은 현재 editscreen.h .cpp 에 구현된 사항을 mainwindow로 옮긴다.
2. 마찬가지로 .ui 작업중인 지수는 workspace.ui의 기능을 mainwindow.ui에 구현한다.
  -> 문제발생. 둘다 mainwindow.h, mainwindow.cpp에 작업해야함.

**Comment by jisoooo** [comment]
스태이터스바가 뭐죠...? 메뉴바는 알겠는데
그 프로그램 동작 2번의 경우 메뉴선택 위젯이 나오고 edit화면은 메뉴선택 위젯에서 무언가를 눌러야 나와요, 떠있는 상태가 아닙니다.
떠있는 상태로 만들까요?
1. 11. 1. 오후 6:21에 "kokosoko59" notifications@github.com님이 작성:

**Comment by jinsk44** [comment]
스테이터스바는 아마 하단에 위치한 부분을 말하는거 같구, 가장 기본화면을 edit화면(mainwindow)로 하자는 얘기로 이해하면 될것같아요.

그리고, 어려운게 아니라면, 저는 mainwindow가 가장 밑에 떠있고, 그 뒤에 filemanage화면을 띄우는 방식이 좋을 것 같아요. filemanage가 순차적으로 부르는 방식으로 구현한 것 같은데 그거보다는 mainwindow에서 부르고 응답받는 형태가 좋을것 같습니다.
(예를 들면 나중에 마인드맵을 쓰다가,, 새파일을 여는 등의 액션을 할 때에 더 자연스러울 것 같아요.)
